/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backend liveness check. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connectivity smoke test for renderer -> main -> backend chain. */
        get: operations["testPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        ApiMeta: {
            code: string;
            message: string;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
        };
        ApiError: components["schemas"]["ApiMeta"] & {
            /** @enum {string} */
            code: "AUTH_INVALID_TOKEN";
            /** @enum {boolean} */
            success: false;
        };
        TestPingData: {
            /** @enum {string} */
            service: "cosmosh-backend";
            /** @enum {string} */
            mode: "electron-main";
            /** @enum {boolean} */
            authenticated: true;
            capabilities: ("ssh" | "sftp")[];
        };
        TestPingSuccess: components["schemas"]["ApiMeta"] & {
            /** @enum {string} */
            code: "TEST_PING_OK";
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["TestPingData"];
        };
    };
    responses: never;
    parameters: {
        LocaleHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    testPing: {
        parameters: {
            query?: never;
            header?: {
                "x-cosmosh-locale"?: components["parameters"]["LocaleHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful ping response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestPingSuccess"];
                };
            };
            /** @description Authentication failed. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
