/**
 * This file is auto-generated from openapi/cosmosh.openapi.yaml.
 * Do not edit this file directly. Run "pnpm --filter @cosmosh/api-contract generate" instead.
 */

export const API_PATHS = {
  health: '/api/health',
  testPing: '/api/v1/test/ping',
} as const;

export const API_HEADERS = {
  internalToken: 'x-cosmosh-internal-token',
  locale: 'x-cosmosh-locale',
} as const;

export const API_CODES = {
  authInvalidToken: 'AUTH_INVALID_TOKEN',
  testPingOk: 'TEST_PING_OK',
} as const;

export const API_CAPABILITIES = ['ssh', 'sftp'] as const;
