/**
 * This file is auto-generated from openapi/cosmosh.openapi.yaml.
 * Do not edit this file directly. Run "pnpm --filter @cosmosh/api-contract generate" instead.
 */

export const API_PATHS = {
  health: '/api/health',
  testPing: '/api/v1/test/ping',
  sshListServers: '/api/v1/ssh/servers',
  sshCreateServer: '/api/v1/ssh/servers',
  sshUpdateServer: '/api/v1/ssh/servers/{serverId}',
  sshGetServerCredentials: '/api/v1/ssh/servers/{serverId}/credentials',
  sshDeleteServer: '/api/v1/ssh/servers/{serverId}/credentials',
  sshListFolders: '/api/v1/ssh/folders',
  sshCreateFolder: '/api/v1/ssh/folders',
  sshUpdateFolder: '/api/v1/ssh/folders/{folderId}',
  sshDeleteFolder: '/api/v1/ssh/folders/{folderId}',
  sshListTags: '/api/v1/ssh/tags',
  sshCreateTag: '/api/v1/ssh/tags',
  sshCreateSession: '/api/v1/ssh/sessions',
  sshCloseSession: '/api/v1/ssh/sessions/{sessionId}',
  sshTrustFingerprint: '/api/v1/ssh/trusted-host-keys',
} as const;

export const API_HEADERS = {
  internalToken: 'x-cosmosh-internal-token',
  locale: 'x-cosmosh-locale',
} as const;

export const API_CODES = {
  authInvalidToken: 'AUTH_INVALID_TOKEN',
  sshValidationFailed: 'SSH_VALIDATION_FAILED',
  sshServerConflict: 'SSH_SERVER_CONFLICT',
  sshFolderConflict: 'SSH_FOLDER_CONFLICT',
  sshTagConflict: 'SSH_TAG_CONFLICT',
  sshNotFound: 'SSH_NOT_FOUND',
  sshHostUntrusted: 'SSH_HOST_UNTRUSTED',
  sshSessionNotFound: 'SSH_SESSION_NOT_FOUND',
  testPingOk: 'TEST_PING_OK',
  sshServerListOk: 'SSH_SERVER_LIST_OK',
  sshServerCreateOk: 'SSH_SERVER_CREATE_OK',
  sshServerUpdateOk: 'SSH_SERVER_UPDATE_OK',
  sshServerCredentialsOk: 'SSH_SERVER_CREDENTIALS_OK',
  sshFolderListOk: 'SSH_FOLDER_LIST_OK',
  sshFolderCreateOk: 'SSH_FOLDER_CREATE_OK',
  sshFolderUpdateOk: 'SSH_FOLDER_UPDATE_OK',
  sshTagListOk: 'SSH_TAG_LIST_OK',
  sshTagCreateOk: 'SSH_TAG_CREATE_OK',
  sshSessionCreateOk: 'SSH_SESSION_CREATE_OK',
  sshTrustFingerprintOk: 'SSH_TRUST_FINGERPRINT_OK',
} as const;

export const API_CAPABILITIES = ['ssh', 'sftp'] as const;
